// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrss067r3Nu4xc5wymD8nnsxnjZdiiWFE',
    appId: '1:654294151538:web:07fac121dbdd7d6150adeb',
    messagingSenderId: '654294151538',
    projectId: 'tutamfit',
    authDomain: 'tutamfit.firebaseapp.com',
    storageBucket: 'tutamfit.firebasestorage.app',
    measurementId: 'G-L0SZS9KP89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJwst_wQFs2lVLaXcQR6r5imsKqpfAm8E',
    appId: '1:654294151538:android:3aaa1f5dc40b002a50adeb',
    messagingSenderId: '654294151538',
    projectId: 'tutamfit',
    storageBucket: 'tutamfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkS5bMXgO9qMzhmH5dHGd1fOYJXw0dM9M',
    appId: '1:654294151538:ios:89a560df2fc8ebee50adeb',
    messagingSenderId: '654294151538',
    projectId: 'tutamfit',
    storageBucket: 'tutamfit.firebasestorage.app',
    iosBundleId: 'com.example.tutamFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkS5bMXgO9qMzhmH5dHGd1fOYJXw0dM9M',
    appId: '1:654294151538:ios:89a560df2fc8ebee50adeb',
    messagingSenderId: '654294151538',
    projectId: 'tutamfit',
    storageBucket: 'tutamfit.firebasestorage.app',
    iosBundleId: 'com.example.tutamFit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrss067r3Nu4xc5wymD8nnsxnjZdiiWFE',
    appId: '1:654294151538:web:cfaadafd070e01d950adeb',
    messagingSenderId: '654294151538',
    projectId: 'tutamfit',
    authDomain: 'tutamfit.firebaseapp.com',
    storageBucket: 'tutamfit.firebasestorage.app',
    measurementId: 'G-QTX5XK05E4',
  );
}
